.PHONY: clean All

All:
	@echo "----------Building project:[ reorder_from_index - Debug ]----------"
	@cd "reorder_from_index" && "$(MAKE)" -f  "reorder_from_index.mk"
clean:
	@echo "----------Cleaning project:[ reorder_from_index - Debug ]----------"
	@cd "reorder_from_index" && "$(MAKE)" -f  "reorder_from_index.mk" clean
