.PHONY: clean All

All:
	@echo "----------Building project:[ rearrange_positive_negative - Debug ]----------"
	@cd "rearrange_positive_negative" && "$(MAKE)" -f  "rearrange_positive_negative.mk"
clean:
	@echo "----------Cleaning project:[ rearrange_positive_negative - Debug ]----------"
	@cd "rearrange_positive_negative" && "$(MAKE)" -f  "rearrange_positive_negative.mk" clean
