.PHONY: clean All

All:
	@echo "----------Building project:[ array[i]=i - Debug ]----------"
	@cd "array[i]=i" && "$(MAKE)" -f  "array[i]=i.mk"
clean:
	@echo "----------Cleaning project:[ array[i]=i - Debug ]----------"
	@cd "array[i]=i" && "$(MAKE)" -f  "array[i]=i.mk" clean
